export let HISTORY_SEC_2 = [
    {
      id: 6,
      child_id: [18, "Oan Yohan"],
      child_nik: "7171000017",
      expected_month_age: 9,
      actual_month_age: 9,
      vaccine_month_category: "84",
      vaccine_list_ids: "Hepatitis 0 (HB0)",
      expected_date: "2022-01-01",
      register_date: "2022-01-01",
      child_weight: 27,
      child_height: 112,
      vaccinator: "Kunai",
      vaccinator_location: "Wenang",
      state: "right_on_time",
    },
    {
      id: 7,
      child_id: [19, "Priska Pontius"],
      child_nik: "7171000018",
      expected_month_age: 5,
      actual_month_age: 5,
      vaccine_month_category: "18",
      vaccine_list_ids: "BCG, OPV1",
      expected_date: "2021-02-16",
      register_date: "2021-02-19",
      child_weight: 16,
      child_height: 96,
      vaccinator: "Kunai",
      vaccinator_location: "Wenang",
      state: "past_due_date",
    },
    {
      id: 8,
      child_id: [20, "Hizkia Matindas"],
      child_nik: "7171000019",
      expected_month_age: 8,
      actual_month_age: 8,
      vaccine_month_category: "120",
      vaccine_list_ids: "BCG, OPV1",
      expected_date: "2021-02-16",
      register_date: "2021-02-19",
      child_weight: 25,
      child_height: 138,
      vaccinator: "Kunai",
      vaccinator_location: "Wenang",
      state: "past_due_date",
    },
    {
      id: 9,
      child_id: [21, "Gerald Pasuhuk"],
      child_nik: "7171000020",
      expected_month_age: 2,
      actual_month_age: 2,
      vaccine_month_category: "18",
      vaccine_list_ids: "BCG, OPV1",
      expected_date: "2021-02-16",
      register_date: "2021-02-19",
      child_weight: 21,
      child_height: 105,
      vaccinator: "Kunai",
      vaccinator_location: "Wenang",
      state: "past_due_date",
    },
    {
      id: 10,
      child_id: [22, "Marcelino Pasuhuk"],
      child_nik: "7171000021",
      expected_month_age: 3,
      actual_month_age: 3,
      vaccine_month_category: "1",
      vaccine_list_ids: "BCG, OPV1",
      expected_date: "2021-02-16",
      register_date: "2021-02-19",
      child_weight: 6,
      child_height: 64,
      vaccinator: "Kunai",
      vaccinator_location: "Wenang",
      state: "past_due_date",
    },
  ];
 