export let HISTORY_SEC_1 = [
  {
    id: 1,
    child_id: [12, "Vira Maode"],
    child_nik: "7171000011",
    expected_month_age: 0,
    actual_month_age: 0,
    vaccine_month_category: "0",
    vaccine_list_ids: "Hepatitis 0 (HB0)",
    expected_date: "2022-01-01 ",
    register_date: "2022-01-01 ",
    child_weight: 2,
    child_height: 20,
    vaccinator: "Kunai",
    vaccinator_location: "Wenang",
    state: "right_on_time",
  },
  {
    id: 2,
    child_id: [13, "Nia Maure"],
    child_nik: "7171000012",
    expected_month_age: 12,
    actual_month_age: 15,
    vaccine_month_category: "12",
    vaccine_list_ids: "PCV 3",
    expected_date: "2021-02-16 ",
    register_date: "2022-05-14 ",
    child_weight: 8,
    child_height: 82,
    vaccinator: "Jekson",
    vaccinator_location: "Singkil",
    state: "pass_due_date",
  },
  {
    id: 4,
    child_id: [14, "Nina Saraun"],
    child_nik: "7171000013",
    expected_month_age: 120,
    actual_month_age: 120,
    vaccine_month_category: "120",
    vaccine_list_ids: "Td",
    expected_date: "2022-02-01 ",
    register_date: "2022-02-01 ",
    child_weight: 40,
    child_height: 130,
    vaccinator: "Layla",
    vaccinator_location: "Malalayang",
    state: "right_on_time",
  },
  {
    id: 5,
    child_id: [15, "Rex Sigar"],
    child_nik: "7171000014",
    expected_month_age: 84,
    actual_month_age: 84,
    vaccine_month_category: "84",
    vaccine_list_ids: "Td",
    expected_date: "2022-04-12 ",
    register_date: "2022-04-12 ",
    child_weight: 40,
    child_height: 130,
    vaccinator: "Selfi",
    vaccinator_location: "Sario",
    state: "right_on_time",
  },
  {
    id: 6,
    child_id: [16, "Yos Purukan"],
    child_nik: "7171000015",
    expected_month_age: 120,
    actual_month_age: 154,
    vaccine_month_category: "120",
    vaccine_list_ids: "Td",
    expected_date: "2019-06-20 ",
    register_date: "2022-05-14 ",
    child_weight: 40,
    child_height: 130,
    vaccinator: "Stif",
    vaccinator_location: "Malalayang",
    state: "pass_due_date",
  },
  {
    id: 7,
    child_id: [17, "Ayu Sari"],
    child_nik: "7171000016",
    expected_month_age: 120,
    actual_month_age: 120,
    vaccine_month_category: "120",
    vaccine_list_ids: "Td",
    expected_date: "2021-03-16 ",
    register_date: "2021-03-16 ",
    child_weight: 40,
    child_height: 130,
    vaccinator: "Regina",
    vaccinator_location: "Mapanget",
    state: "right_on_time",
  },
];
